### ISSUE TITLE
Generate immediatly after Reset creates an error

### ISSUE THREAD

**Issue by Ahmed-jerbi** [Ahmed-jerbi/ScriptGenerator#3]

**Comment by Lukas595** [comment]
I think this happens because in the `resetButton_Click` we remove all elements of the document, so when we hit generate button the call of `xdoc.Root.LastNode.AddAfterSelf(...)` points on a null object. I also noticed that the file element is missing after a reset.
I will working on a fix,

**Comment by Ahmed-jerbi** [comment]
Yes exactly, i now added a check if LastNode != null before Adding the node.
The <file> element is not needed anyway
