### ISSUE TITLE
Export ignores path and name defined in script file

### ISSUE THREAD

**Issue by Lukas595** [Ahmed-jerbi/ScriptGenerator#5]
When exporting, the path and file name defined in the script are ignored and instead the path "C:\Users\Public\Documents\VIOSO\Anyblend\Export" and the name of the calibration file are used.

**Comment by Ahmed-jerbi** [comment]
> 
> 
> When exporting, the path and file name defined in the script are ignored and instead the path "C:\Users\Public\Documents\VIOSO\Anyblend\Export" and the name of the calibration file are used.

Yes, There's a typo in the generated export XML: "task" is written "taks"

**Comment by Lukas595** [comment]
I will fix it

**Comment by Ahmed-jerbi** [comment]
Thanks Lukas, I just pushed a new commit with this fixed already
